SELECT HR_E.EMP_NO, HR_E.EMP_NAME, 
CASE 
    WHEN AVG(HR_G.SCORE) >=96 THEN 'S'
    WHEN AVG(HR_G.SCORE) >= 90 THEN 'A'
    WHEN AVG(HR_G.SCORE) >= 80 THEN 'B'
ELSE 'C' END AS GRADE, 

CASE
    WHEN AVG(HR_G.SCORE) >= 96 THEN HR_E.SAL * 0.2
    WHEN AVG(HR_G.SCORE) >= 90 THEN HR_E.SAL * 0.15
    WHEN AVG(HR_G.SCORE) >= 80 THEN HR_E.SAL * 0.1
ELSE 0 END AS BONUS
FROM HR_DEPARTMENT AS HR_D
JOIN HR_EMPLOYEES AS HR_E ON HR_D.DEPT_ID = HR_E.DEPT_ID
JOIN HR_GRADE AS HR_G ON HR_E.EMP_NO = HR_G.EMP_NO
GROUP BY HR_E.EMP_NO, HR_E.EMP_NAME
ORDER BY HR_E.EMP_NO ASC
