SELECT SUM(HR_G.SCORE) AS SCORE, HR_E.EMP_NO, HR_E.EMP_NAME, HR_E.POSITION, HR_E.EMAIL
FROM HR_DEPARTMENT AS HR_D
JOIN HR_EMPLOYEES AS HR_E ON HR_D.DEPT_ID = HR_E.DEPT_ID
JOIN HR_GRADE AS HR_G ON HR_E.EMP_NO = HR_G.EMP_NO
GROUP BY HR_G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;