SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE 1=1 
AND PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT AS FP WHERE FP.CATEGORY = FOOD_PRODUCT.CATEGORY) 
AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC